move pipe check to just after npm run

diff --git a/bin/compile_nodejs b/bin/compile_nodejs
--- a/bin/compile_nodejs
+++ b/bin/compile_nodejs
@@ -69,20 +69,18 @@ fi
 # install dependencies with npm
 echo "-----> Installing dependencies with npm $NPM_VERSION"
 cd $BUILD_DIR
-#HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js install 2>&1 | indent
 for pkg in $(cat requirements.npm); do
     # TODO: read line by line and skip empty
     if [[ ! $(echo pkg) = '#'* ]]; then
         HOME="$BUILD_DIR" $VENDORED_NODE/bin/node $VENDORED_NPM/cli.js install $pkg 2>&1 | indent
+        if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+          echo " !     Failed to install dependencies with npm"
+          exit 1
+        else
+          echo "       Dependencies installed"
+        fi
     fi
 done
-
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to install dependencies with npm"
-  exit 1
-else
-  echo "       Dependencies installed"
-fi
 
 # repack cache with new assets
 if [ -d $CACHE_TARGET_DIR ]; then
